const primary = "#6C63FF";
const primaryLight = "#8B84FF";
const primaryDark = "#4B44CC";

export default {
  light: {
    text: "#0F0F23",
    textSecondary: "#6B7280",
    background: "#F8F9FE",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
    tint: primary,
    tintLight: primaryLight,
    tintDark: primaryDark,
    tabIconDefault: "#9CA3AF",
    tabIconSelected: primary,
    destructive: "#EF4444",
    success: "#10B981",
    warning: "#F59E0B",
    info: "#3B82F6",
    overlay: "rgba(0,0,0,0.4)",
    inputBackground: "#F3F4F6",
    shadow: "rgba(0,0,0,0.08)",
    chatUser: primary,
    chatAssistant: "#F3F4F6",
    chatUserText: "#FFFFFF",
    chatAssistantText: "#0F0F23",
    taskHigh: "#EF4444",
    taskMedium: "#F59E0B",
    taskLow: "#10B981",
    calendarToday: primary,
    calendarEvent: primary,
    emailUnread: primary,
  },
  dark: {
    text: "#F9FAFB",
    textSecondary: "#9CA3AF",
    background: "#0A0A1A",
    surface: "#111128",
    surfaceElevated: "#1C1C3A",
    border: "#2D2D4D",
    borderLight: "#1F1F3A",
    tint: primaryLight,
    tintLight: "#A89BFF",
    tintDark: primary,
    tabIconDefault: "#6B7280",
    tabIconSelected: primaryLight,
    destructive: "#F87171",
    success: "#34D399",
    warning: "#FBBF24",
    info: "#60A5FA",
    overlay: "rgba(0,0,0,0.6)",
    inputBackground: "#1C1C3A",
    shadow: "rgba(0,0,0,0.4)",
    chatUser: primary,
    chatAssistant: "#1C1C3A",
    chatUserText: "#FFFFFF",
    chatAssistantText: "#F9FAFB",
    taskHigh: "#F87171",
    taskMedium: "#FBBF24",
    taskLow: "#34D399",
    calendarToday: primaryLight,
    calendarEvent: primaryLight,
    emailUnread: primaryLight,
  },
};
